[project]
name = "seminar-3"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "requests>=2.32.5",
]

[tool.pyright]
venv = ".venv"
venvPath = "."
